// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "wilayah/domain"

	mock "github.com/stretchr/testify/mock"
)

// KotaUsecase is an autogenerated mock type for the KotaUsecase type
type KotaUsecase struct {
	mock.Mock
}

// AddKota provides a mock function with given fields: newKota
func (_m *KotaUsecase) AddKota(newKota domain.Kota) (int, error) {
	ret := _m.Called(newKota)

	var r0 int
	if rf, ok := ret.Get(0).(func(domain.Kota) int); ok {
		r0 = rf(newKota)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Kota) error); ok {
		r1 = rf(newKota)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteKota provides a mock function with given fields: id
func (_m *KotaUsecase) DeleteKota(id int) (int, error) {
	ret := _m.Called(id)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllKota provides a mock function with given fields:
func (_m *KotaUsecase) GetAllKota() ([]domain.Kota, error) {
	ret := _m.Called()

	var r0 []domain.Kota
	if rf, ok := ret.Get(0).(func() []domain.Kota); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Kota)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateKota provides a mock function with given fields: id, UpdateKota
func (_m *KotaUsecase) UpdateKota(id int, UpdateKota domain.Kota) (int, error) {
	ret := _m.Called(id, UpdateKota)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, domain.Kota) int); ok {
		r0 = rf(id, UpdateKota)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.Kota) error); ok {
		r1 = rf(id, UpdateKota)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewKotaUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewKotaUsecase creates a new instance of KotaUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewKotaUsecase(t mockConstructorTestingTNewKotaUsecase) *KotaUsecase {
	mock := &KotaUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
