// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "wilayah/domain"

	mock "github.com/stretchr/testify/mock"
)

// MemberData is an autogenerated mock type for the MemberData type
type MemberData struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *MemberData) Delete(id int) (int, error) {
	ret := _m.Called(id)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *MemberData) GetAll() ([]domain.Member, error) {
	ret := _m.Called()

	var r0 []domain.Member
	if rf, ok := ret.Get(0).(func() []domain.Member); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Member)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertMember provides a mock function with given fields: newMember
func (_m *MemberData) InsertMember(newMember domain.Member) (int, error) {
	ret := _m.Called(newMember)

	var r0 int
	if rf, ok := ret.Get(0).(func(domain.Member) int); ok {
		r0 = rf(newMember)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Member) error); ok {
		r1 = rf(newMember)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, updatedData
func (_m *MemberData) Update(id int, updatedData domain.Member) (int, error) {
	ret := _m.Called(id, updatedData)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, domain.Member) int); ok {
		r0 = rf(id, updatedData)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.Member) error); ok {
		r1 = rf(id, updatedData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMemberData interface {
	mock.TestingT
	Cleanup(func())
}

// NewMemberData creates a new instance of MemberData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMemberData(t mockConstructorTestingTNewMemberData) *MemberData {
	mock := &MemberData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
