// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "wilayah/domain"

	mock "github.com/stretchr/testify/mock"
)

// ProvinsiData is an autogenerated mock type for the ProvinsiData type
type ProvinsiData struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *ProvinsiData) Delete(id int) (int, error) {
	ret := _m.Called(id)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *ProvinsiData) GetAll() ([]domain.Provinsi, error) {
	ret := _m.Called()

	var r0 []domain.Provinsi
	if rf, ok := ret.Get(0).(func() []domain.Provinsi); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Provinsi)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertProvinsi provides a mock function with given fields: newProvinsi
func (_m *ProvinsiData) InsertProvinsi(newProvinsi domain.Provinsi) (int, error) {
	ret := _m.Called(newProvinsi)

	var r0 int
	if rf, ok := ret.Get(0).(func(domain.Provinsi) int); ok {
		r0 = rf(newProvinsi)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Provinsi) error); ok {
		r1 = rf(newProvinsi)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, updatedData
func (_m *ProvinsiData) Update(id int, updatedData domain.Provinsi) (int, error) {
	ret := _m.Called(id, updatedData)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, domain.Provinsi) int); ok {
		r0 = rf(id, updatedData)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.Provinsi) error); ok {
		r1 = rf(id, updatedData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewProvinsiData interface {
	mock.TestingT
	Cleanup(func())
}

// NewProvinsiData creates a new instance of ProvinsiData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProvinsiData(t mockConstructorTestingTNewProvinsiData) *ProvinsiData {
	mock := &ProvinsiData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
